export class Actividad{
    id: number;
    nombre: string;
    descripcion: string = null;
    usuarioCreo: string;
    usuarioActualizo: string;
    fechaCreacion: string;
    fechaActualizacion: string;
    fechaInicio: string;
    fechaFin: string;
    actividadTipoid: number;
    actividadtiponombre: string;
    porcentajeAvance: number;
    programa: number = null;
    subprograma: number = null;
    proyecto: number = null;
    actividad: number = null;
    obra: number = null;
    renglon: number = null;
    ubicacionGeografica: number = null;
    longitud: number = null;
    latitud: number = null;
    predecesorId: number;
    predecesorTipo: number;
    duracion: number;
    duracionDimension: string;
    costo: number;
    acumulacionCostoid: number;
    acumulacionCostoNombre: string;
    presupuestoModificado: number;
    presupuestoPagado: number;
    presupuestoVigente: number;
    presupuestoDevengado: number;
    avanceFinanciero: number;
    estado: number;
    proyectoBase: number;
    tieneHijos: boolean = false;
    fechaInicioReal: Date;
    fechaFinReal: Date;
    congelado: number;
    fechaElegibilidad: Date;
    fechaCierre: Date;
    inversionNueva: number;
    objetoId: number = null;
    objetoTipo: number = null;

    camposDinamicos: string;
    asignacionroles: string;
}