using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SActividadPropiedad.Controllers
{
    /// <summary>
    /// A class which represents the ComponentePropiedadValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class ActividadPropiedadValidator : AbstractValidator<JObject>
	{
		public ActividadPropiedadValidator() 
		{
            //RuleFor(actividad_propiedad => actividad_propiedad["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int32));
            RuleFor(actividad_propiedad => actividad_propiedad["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
            //RuleFor(actividad_propiedad => actividad_propiedad["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'descripcion' to type " + typeof(String)).MaximumLength(2000);
            //RuleFor(actividad_propiedad => actividad_propiedad["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
            //RuleFor(actividad_propiedad => actividad_propiedad["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
            //RuleFor(actividad_propiedad => actividad_propiedad["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
            //RuleFor(actividad_propiedad => actividad_propiedad["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
            RuleFor(actividad_propiedad => actividad_propiedad["datoTipoid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'datoTipoid' to type " + typeof(Int32));
            //RuleFor(actividad_propiedad => actividad_propiedad["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(actividad_propiedad => { return GenericValidatorType.ValidateType(actividad_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));

        }
    }
}
