using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace STipoAdquisicion.Controllers
{
    /// <summary>
    /// A class which represents the TipoAdquisicionValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class TipoAdquisicionValidator : AbstractValidator<JObject>
	{
		public TipoAdquisicionValidator() 
		{
			//RuleFor(tipo_adquisicion => tipo_adquisicion["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(Int64)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int64));
			RuleFor(tipo_adquisicion => tipo_adquisicion["cooperantecodigo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'cooperantecodigo' to type " + typeof(Int32));
			RuleFor(tipo_adquisicion => tipo_adquisicion["cooperanteejercicio"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'cooperanteejercicio' to type " + typeof(Int32));
			RuleFor(tipo_adquisicion => tipo_adquisicion["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
			//RuleFor(tipo_adquisicion => tipo_adquisicion["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(tipo_adquisicion => tipo_adquisicion["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(tipo_adquisicion => tipo_adquisicion["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
			//RuleFor(tipo_adquisicion => tipo_adquisicion["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
			//RuleFor(tipo_adquisicion => tipo_adquisicion["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));
			RuleFor(tipo_adquisicion => tipo_adquisicion["convenioCdirecta"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(tipo_adquisicion => { return GenericValidatorType.ValidateType(tipo_adquisicion, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'convenioCdirecta' to type " + typeof(Int32));
			
		}
	}
}
